### ISSUE TITLE
[Bug]: Ender chest size is hardcoded

### ISSUE THREAD

**Issue by Yupoman** [Fuzss/easyshulkerboxes#32]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

https://www.curseforge.com/minecraft/mc-mods/inventorio-forge

One of the features of Inventorio is being able to double the space of the ender chest with an enchantment. Easy Shulker Boxes works well with this expansion (adds and removes items normally), the only problem is that you can't visually see the entire chest.

I'm not sure but I think it's just a problem with the interface of this mod, it would be great if they could make it 100% compatible.

**Comment by Fuzss** [comment]
Does it work in 1.20.4 for v20.4.2?

**Comment by Fuzss** [comment]
Please try v20.4.4 now, it should fix the missing rows. Does it work for you?

**Comment by Fuzss** [comment]
Alright, one more try in v20.4.5.

**Comment by SageofTurtles** [comment]
I'm still having this exact same issue in Forge 1.20.1 with the latest version of the mod.  Is this something that will ever be patched?
